# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions:
  actions: write
  contents: write

on:
  push:
    paths: [ "**.cs" ]
  pull_request:
    paths: [ "**.cs" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: 设置 .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: 还原依赖项
      run: dotnet restore

    - name: 推送 win-x64
      run: |
        dotnet publish Program\Program.csproj -o Release\win-x64 -r win-x64 --framework net9.0 -p:PublishSingleFile=true -p:CopyOutputSymbolsToPublishDirectory=false
    - name: 推送 linux-x64
      run: |
        dotnet publish Program\Program.csproj -o Release\linux-x64 -r linux-x64 --framework net9.0 -p:PublishSingleFile=true -p:CopyOutputSymbolsToPublishDirectory=false
    - name: 推送 linux-arm64
      run: |
        dotnet publish Program\Program.csproj -o Release\linux-arm64 -r linux-arm64 --framework net9.0 -p:PublishSingleFile=true -p:CopyOutputSymbolsToPublishDirectory=false

    - name: 上传 win-x64构建产物
      uses: actions/upload-artifact@v4.3.1
      with:
        name: HyacineDH-win-64
        path: Release\win-x64

    - name: 上传 linux-x64构建产物
      uses: actions/upload-artifact@v4.3.1
      with:
        name: HyacineDH-linux-x64
        path: Release\linux-x64

    - name: 上传 linux-arm64构建产物
      uses: actions/upload-artifact@v4.3.1
      with:
        name: HyacineDH-linux-arm64
        path: Release\linux-arm64
